# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py

add("http://rss.slashdot.org/slashdot/Slashdot")
add("http://reddit.com/r/netsec/.rss")
add("http://www.securityfocus.com/rss/news.xml")
add("http://www.2600.com/rss.xml")
add("http://isc.incidents.org/rssfeed.xml")
add("http://www.schneier.com/blog/index.xml")
add("http://blog.g0tmi1k.com/feeds/posts/default")
add("https://www.corelan.be/index.php/feed/")
add("https://community.rapid7.com/community/feeds/allcontent?community=2003")
add("http://www.securityfocus.com/rss/vulnerabilities.xml")
