#!/usr/bin/env bash
PKG_DB_PATH="work/repository"
PKG=obkey
UPSTREAM=https://aur.archlinux.org/obkey.git 
mkdir -pv "$PKG_DB_PATH"
[[ -e /tmp/$PKG ]] && rm -rf /tmp/$PKG
git clone $UPSTREAM /tmp/$PKG
( cd /tmp/$PKG && makepkg -s )
sudo repo-add $PKG_DB_PATH/work-repository.db.tar.gz /tmp/$PKG/$PKG*.pkg.tar.xz
cp /tmp/$PKG/$PKG*.pkg.tar.xz $PKG_DB_PATH 
